const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium,webkit}=require('playwright');
const ROOT=path.resolve(__dirname,'../..');
const OUT=path.join(ROOT,'_browser_evidence/v365');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json'};

function server(){return http.createServer((req,res)=>{const pathname=new URL(req.url,'http://127.0.0.1').pathname;const rel=pathname==='/'||pathname==='/index.html'?'app/base-shell-v365.html':decodeURIComponent(pathname).replace(/^\/+/, '');const target=path.resolve(ROOT,rel);if(!target.startsWith(ROOT+path.sep)||!fs.existsSync(target)||!fs.statSync(target).isFile()){res.writeHead(404);res.end('not found');return}const body=fs.readFileSync(target);res.writeHead(200,{'content-type':types[path.extname(target)]||'application/octet-stream','content-length':body.length,'cache-control':'no-store'});res.end(body)})}
async function stable(page){const deadline=Date.now()+45000;for(let i=0;i<8;i++){const remain=Math.max(1000,deadline-Date.now());await page.waitForLoadState('load',{timeout:remain});await page.waitForFunction(()=>window.FEQUEST_APP_BOOT_COMPLETE===true&&window.__FEQ_PAGESHOW_SEEN===true,null,{timeout:remain});await page.waitForFunction(()=>navigator.serviceWorker.controller?.state==='activated',null,{timeout:remain});const origin=await page.evaluate(()=>performance.timeOrigin);await page.waitForTimeout(750);if(await page.evaluate(o=>performance.timeOrigin===o&&window.FEQUEST_APP_BOOT_COMPLETE===true,o))return;if(Date.now()>=deadline)break}throw new Error('stable boot boundary not reached')}
async function layout(root){return root.evaluate(node=>{const blocks=[node,...node.querySelectorAll('section,div,p,h4,figcaption,code')];return{overflows:blocks.filter(n=>n.scrollWidth>n.clientWidth+1).map(n=>n.className||n.tagName),documentOverflow:document.documentElement.scrollWidth>innerWidth+1,nodeWidths:[...node.querySelectorAll('[data-ll-node],[data-ll-trace-node]')].map(n=>n.getBoundingClientRect().width)}})}

async function runCase(type,name,viewport,isMobile=false){const browser=await type.launch();const context=await browser.newContext({viewport,locale:'ja-JP',isMobile,hasTouch:isMobile,deviceScaleFactor:isMobile?2:1});const page=await context.newPage();await page.addInitScript(()=>{window.__FEQ_PAGESHOW_SEEN=false;addEventListener('pageshow',()=>window.__FEQ_PAGESHOW_SEEN=true,{once:true})});const errors=[],checks=[],metrics={};page.on('pageerror',e=>errors.push(String(e)));const check=(label,value)=>{checks.push({label,pass:Boolean(value)});if(!value)throw new Error(label)};const snap=async(selector,suffix)=>{const n=page.locator(selector);await n.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(OUT,`${name}-${suffix}-context.png`)});await n.screenshot({path:path.join(OUT,`${name}-${suffix}.png`)})};try{const response=await page.goto(globalThis.__BASE__,{waitUntil:'load',timeout:60000});await stable(page);check('HTTP 200 and v365 runtime',response.status()===200&&await page.evaluate(()=>APP_VERSION==='v365'));const before=await page.evaluate(()=>({progress:{...profile.lessonProgress},bProgress:{...profile.bProgress},xp:profile.xp}));
  await page.evaluate(()=>startLesson('core_14_04'));check('scope excludes other topics',await page.locator('.ll-figure-v365').count()===0&&await page.locator('.core-critical-path-v359').isVisible());
  await page.evaluate(()=>startLesson('core_03_01'));const figure=page.locator('.ll-figure-v365');await figure.waitFor({state:'visible'});check('one static figure',await figure.count()===1);check('logical nodes A C D',JSON.stringify(await page.locator('.ll-chain-v365 [data-ll-node]').evaluateAll(ns=>ns.map(n=>n.dataset.llNode)))==='["A","C","D"]');check('next fields C D null',JSON.stringify(await page.locator('.ll-chain-v365 [data-ll-node] code').allTextContents())==='["next: C","next: D","next: null"]');check('memory order explicit',(await page.locator('.ll-memory-v365').innerText()).replace(/\s/g,'').includes('100A260D420C'));check('safe insertion order',JSON.stringify(await page.locator('.ll-rewire-v365 code').allTextContents())==='["B.next ← C","A.next ← B"]');check('no controls or gate',await figure.locator('button').count()===0&&await page.evaluate(()=>lessonInteractiveDone));metrics.core=await layout(figure);check('core fits viewport',metrics.core.overflows.length===0&&!metrics.core.documentOverflow&&Math.min(...metrics.core.nodeWidths)>=80);await snap('.ll-figure-v365','core');await page.evaluate(()=>startLesson('core_03_01'));check('rerender stays unique',await page.locator('.ll-figure-v365').count()===1);
  await page.evaluate(()=>{showScreen('trace',{instant:true});startBExercise('linked_list');const step=currentB.steps.find(s=>s.currentNode==='B'&&(s.visited||[]).includes('B'));if(!step)throw new Error('B step missing');renderBVisual(step)});const trace=page.locator('#bVisual .ll-trace-v365');await trace.waitFor({state:'visible'});check('trace nodes and next fields',JSON.stringify(await trace.locator('[data-ll-trace-node] code').allTextContents())==='["next: B","next: C","next: null"]');check('current pointer marks B',await trace.getAttribute('data-ll-current')==='B'&&await trace.locator('.ll-trace-pointer-v365.is-current').count()===1&&(await trace.innerText()).includes('現在の p：B'));check('visited A and B',JSON.stringify(await trace.locator('[data-ll-trace-node].visited').evaluateAll(ns=>ns.map(n=>n.dataset.llTraceNode)))==='["A","B"]');metrics.trace=await layout(trace);check('trace fits viewport',metrics.trace.overflows.length===0&&!metrics.trace.documentOverflow&&Math.min(...metrics.trace.nodeWidths)>=55);await snap('#bVisual .ll-trace-v365','trace');
  const mock=await page.evaluate(()=>bMockVisualHtml({visual:{list:[{id:'A',value:5},{id:'B',value:7},{id:'C',value:9}],currentNode:null,visited:['A','B','C']}}));check('mock uses null pointer renderer',mock.includes('data-ll-current="null"')&&mock.includes('null（末尾まで到達）'));check('answer contracts unchanged',await page.evaluate(()=>B_PREDICTION_CONTRACTS['linked_list:1']==='12'&&B_PREDICTION_CONTRACTS['linked_list:2']==='21'));check('saved learning unchanged',JSON.stringify(await page.evaluate(()=>({progress:{...profile.lessonProgress},bProgress:{...profile.bProgress},xp:profile.xp})))===JSON.stringify(before));check('no errors or recovery UI',errors.length===0&&await page.locator('#fequestAssetRecoveryV365').count()===0);return{name,checks,metrics,errors,pass:true}
}catch(error){try{await page.screenshot({path:path.join(OUT,`${name}-failure.png`),fullPage:true})}catch{}return{name,checks,metrics,errors,error:error.stack||String(error),pass:false}}finally{await context.close();await browser.close()}}

async function main(){fs.mkdirSync(OUT,{recursive:true});const app=server();await new Promise(r=>app.listen(0,'127.0.0.1',r));globalThis.__BASE__=`http://127.0.0.1:${app.address().port}/`;let cases;try{cases=[await runCase(chromium,'desktop-chromium-1366',{width:1366,height:900}),await runCase(chromium,'tablet-chromium-1024',{width:1024,height:768}),await runCase(webkit,'mobile-webkit-390',{width:390,height:844},true),await runCase(webkit,'narrow-webkit-320',{width:320,height:720},true)]}finally{await new Promise(r=>app.close(r))}const report={name:'v365-linked-list-diagrams',cases,result:cases.every(c=>c.pass)?'PASS':'FAIL'};fs.writeFileSync(path.join(OUT,'result.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(report.result!=='PASS')process.exitCode=1}
main().catch(e=>{console.error(e);process.exitCode=1});
