const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium,webkit}=require('playwright');
const ROOT=path.resolve(__dirname,'../..');
const OUT=path.join(ROOT,'_browser_evidence/v366');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json'};
function server(){return http.createServer((req,res)=>{const pathname=new URL(req.url,'http://127.0.0.1').pathname;const rel=pathname==='/'||pathname==='/index.html'?'app/base-shell-v366.html':decodeURIComponent(pathname).replace(/^\/+/, '');const target=path.resolve(ROOT,rel);if(!target.startsWith(ROOT+path.sep)||!fs.existsSync(target)||!fs.statSync(target).isFile()){res.writeHead(404);res.end('not found');return}const body=fs.readFileSync(target);res.writeHead(200,{'content-type':types[path.extname(target)]||'application/octet-stream','content-length':body.length,'cache-control':'no-store'});res.end(body)})}
async function stable(page){const deadline=Date.now()+45000;for(let i=0;i<8;i++){const remain=Math.max(1000,deadline-Date.now());await page.waitForLoadState('load',{timeout:remain});await page.waitForFunction(()=>window.FEQUEST_APP_BOOT_COMPLETE===true&&window.__FEQ_PAGESHOW_SEEN===true,null,{timeout:remain});await page.waitForFunction(()=>navigator.serviceWorker.controller?.state==='activated',null,{timeout:remain});const origin=await page.evaluate(()=>performance.timeOrigin);await page.waitForTimeout(750);if(await page.evaluate(o=>performance.timeOrigin===o&&window.FEQUEST_APP_BOOT_COMPLETE===true,origin))return;if(Date.now()>=deadline)break}throw new Error('stable boot boundary not reached')}
async function layout(root){return root.evaluate(node=>{const blocks=[node,...node.querySelectorAll('section,div,p,h4,figcaption,code')];return{overflows:blocks.filter(n=>n.scrollWidth>n.clientWidth+1).map(n=>n.className||n.tagName),documentOverflow:document.documentElement.scrollWidth>innerWidth+1,cellWidths:[...node.querySelectorAll('[data-search-index],[data-search-trace-index]')].map(n=>n.getBoundingClientRect().width)}})}
async function runCase(type,name,viewport,isMobile=false){const browser=await type.launch();const context=await browser.newContext({viewport,locale:'ja-JP',isMobile,hasTouch:isMobile,deviceScaleFactor:isMobile?2:1});const page=await context.newPage();await page.addInitScript(()=>{window.__FEQ_PAGESHOW_SEEN=false;addEventListener('pageshow',()=>window.__FEQ_PAGESHOW_SEEN=true,{once:true})});const errors=[],checks=[],metrics={};page.on('pageerror',e=>errors.push(String(e)));const check=(label,value)=>{checks.push({label,pass:Boolean(value)});if(!value)throw new Error(label)};const snap=async(selector,suffix)=>{const n=page.locator(selector);await n.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(OUT,`${name}-${suffix}-context.png`)});await n.screenshot({path:path.join(OUT,`${name}-${suffix}.png`)})};try{const response=await page.goto(globalThis.__BASE__,{waitUntil:'load',timeout:60000});await stable(page);check('HTTP 200 and v366 runtime',response.status()===200&&await page.evaluate(()=>APP_VERSION==='v366'));await page.evaluate(()=>{profile.diagnosticCompleted=true;firstRunGuidedSessionV364=false;document.body.classList.remove('fequest-first-run-v364');document.getElementById('firstRunGuidedV364')?.remove()});const before=await page.evaluate(()=>({progress:{...profile.lessonProgress},bProgress:{...profile.bProgress},xp:profile.xp}));
  check('scope excludes other topics',await page.evaluate(()=>coreTopicSearchDiagramViewV366('core_03_02')===''&&coreTopicLinkedListDiagramViewV365('core_03_01').includes('ll-figure-v365')));
  await page.evaluate(()=>startLesson('core_03_03'));
  const figure=page.locator('.search-figure-v366');
  await figure.waitFor({state:'visible'});
  check('one static figure and two panels',await figure.count()===1&&await figure.locator('.search-panel-v366').count()===2);
  check('linear order and result',(await figure.locator('.search-panel-v366.linear').innerText()).includes('6回比較')&&await figure.locator('.search-panel-v366.linear [data-search-index]').count()===7);
  check('binary two-step range',await figure.locator('.search-binary-step-v366').count()===2&&(await figure.locator('.search-panel-v366.binary').innerText()).includes('添字0〜3を探索対象から外す'));
  const figureText=await figure.innerText();
  check('prerequisites and complexity',figureText.includes('未整列でも使える')&&figureText.includes('昇順に整列済みが前提')&&figureText.includes('O(log n)'));
  check('no controls or gate',await figure.locator('button').count()===0&&await page.evaluate(()=>lessonInteractiveDone));
  metrics.core=await layout(figure);
  check('core fits viewport',metrics.core.overflows.length===0&&!metrics.core.documentOverflow&&Math.min(...metrics.core.cellWidths)>=20);
  await snap('.search-figure-v366','core');
  await page.evaluate(()=>startLesson('core_03_03'));
  check('rerender stays unique',await page.locator('.search-figure-v366').count()===1);
  await page.evaluate(()=>{showScreen('trace',{instant:true});startBExercise('linear_search');const step=currentB.steps.find(s=>s.focus===2&&s.state?.i===2);if(!step)throw new Error('linear step missing');renderBVisual(step)});const linear=page.locator('#bVisual .search-trace-v366');await linear.waitFor({state:'visible'});check('linear trace current and checked',await linear.getAttribute('data-search-mode')==='linear'&&await linear.locator('.is-checked').count()===2&&await linear.locator('.is-current').count()===1&&(await linear.innerText()).includes('現在の i：2'));metrics.linear=await layout(linear);check('linear trace fits viewport',metrics.linear.overflows.length===0&&!metrics.linear.documentOverflow&&Math.min(...metrics.linear.cellWidths)>=20);await snap('#bVisual .search-trace-v366','linear-trace');
  await page.evaluate(()=>{startBExercise('binary_search_b');const step=currentB.steps.find(s=>s.state?.low===4&&s.state?.high===6&&s.state?.mid===5&&s.found===5);if(!step)throw new Error;renderBVisual(step)});const binary=page.locator('#bVisual .search-trace-v366');await binary.waitFor({state:'visible'});check('binary trace range and labels',await binary.getAttribute('data-search-mode')==='binary'&&await binary.getAttribute('data-search-low')==='4'&&await binary.getAttribute('data-search-high')==='6'&&await binary.locator('.is-discarded').count()===4&&await binary.locator('.is-found').count()===1&&(await binary.innerText()).includes('low')&&(await binary.innerText()).includes('mid')&&(await binary.innerText()).includes('high'));metrics.binary=await layout(binary);check('binary trace fits viewport',metrics.binary.overflows.length===0&&!metrics.binary.documentOverflow&&Math.min(...metrics.binary.cellWidths)>=20);await snap('#bVisual .search-trace-v366','binary-trace');
  const mock=await page.evaluate(()=>bMockVisualHtml({visual:{array:[2,5,8,12,16,21,30],target:21,searchMode:'binary_search_b',searchState:{low:4,high:6,mid:5},focus:5,found:5}}));check('mini mock uses search renderer',mock.includes('data-search-mode="binary"')&&mock.includes('data-search-low="4"'));const generic=await page.evaluate(()=>bMockVisualHtml({visual:{array:[4,9,2,7],focus:1}}));check('other arrays keep generic renderer',generic.includes('trace-array')&&!generic.includes('search-trace-v366'));check('answer contracts unchanged',await page.evaluate(()=>B_PREDICTION_CONTRACTS['linear_search:1']==='12'&&B_PREDICTION_CONTRACTS['linear_search:2']==='3'&&B_PREDICTION_CONTRACTS['binary_search_b:1']==='4'&&B_PREDICTION_CONTRACTS['binary_search_b:2']==='5'));check('saved learning unchanged',JSON.stringify(await page.evaluate(()=>({progress:{...profile.lessonProgress},bProgress:{...profile.bProgress},xp:profile.xp})))===JSON.stringify(before));check('no errors or recovery UI',errors.length===0&&await page.locator('#fequestAssetRecoveryV366').count()===0);return{name,checks,metrics,errors,pass:true}
}catch(error){try{await page.screenshot({path:path.join(OUT,`${name}-failure.png`),fullPage:true})}catch{}return{name,checks,metrics,errors,error:error.stack||String(error),pass:false}}finally{await context.close();await browser.close()}}
async function main(){fs.mkdirSync(OUT,{recursive:true});const app=server();await new Promise(r=>app.listen(0,'127.0.0.1',r));globalThis.__BASE__=`http://127.0.0.1:${app.address().port}/`;let cases;try{cases=[await runCase(chromium,'desktop-chromium-1366',{width:1366,height:900}),await runCase(chromium,'tablet-chromium-1024',{width:1024,height:768}),await runCase(webkit,'mobile-webkit-390',{width:390,height:844},true),await runCase(webkit,'narrow-webkit-320',{width:320,height:720},true)]}finally{await new Promise(r=>app.close(r))}const report={name:'v366-search-diagrams',cases,result:cases.every(c=>c.pass)?'PASS':'FAIL'};fs.writeFileSync(path.join(OUT,'result.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(report.result!=='PASS')process.exitCode=1}
main().catch(e=>{console.error(e);process.exitCode=1});
