from pathlib import Path
import base64,json,os,re,runpy,subprocess,tempfile

def req(ok,msg):
    if not ok: raise AssertionError(msg)
def context():
    b=os.environ.get('GITHUB_HEAD_REF') or os.environ.get('GITHUB_REF_NAME') or subprocess.check_output(['git','branch','--show-current'],text=True).strip();m=re.fullmatch(r'subject-a-mock-unreached-question-diagnosis-(v(\d+))',b);req(m,'bad v309 branch');return m.group(1),f'v{int(m.group(2))-1}'
def scripts(path):
    h=Path(path).read_text();return '\n'.join(s for s in re.findall(r'<script(?:\s[^>]*)?>(.*?)</script>',h,re.S|re.I) if s.strip() and not s.lstrip().startswith('{'))
def runtime(path):
    js=scripts(path);stub=runpy.run_path('.github/release/runtime_stub.py')['STUB'];tail=r'''
function seeded(seed){let a=seed>>>0;return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
function sourceId(q){return String(q?.sourceId||q?.id||'');}
function complete(xs,i){const day=new Date(Date.UTC(2026,0,1+i)).toISOString().slice(0,10);for(const q of xs){const id=sourceId(q);const st=profile.mockQuestionStats[id]||(profile.mockQuestionStats[id]={seen:0,correct:0,lastSeen:null});st.seen=(st.seen||0)+1;st.lastSeen=day;}}
function prefix(id){const m=String(id).match(/^[A-Za-z]+(?:_[A-Za-z]+)*/);return m?m[0]:String(id).split(/[-_]/)[0];}
function group(rows,key){const o={};for(const q of rows){const k=key(q);o[k]=(o[k]||0)+1;}return Object.fromEntries(Object.entries(o).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])));}
function runMixed(runs){profile.mockQuestionStats={};const exposure={};for(let i=0;i<runs;i++){const mode=i%3===0?'half':'full';Math.random=seeded(3090001+i*7919);const xs=buildMockQuestions(mode);for(const q of xs){const id=sourceId(q);exposure[id]=(exposure[id]||0)+1;}complete(xs,i);}const eligible=QUESTION_BANK.filter(q=>MOCK_CATEGORIES.includes(q.cat)&&MOCK_DIFFICULTY_LEVELS.includes(q.difficulty));const never=eligible.filter(q=>!(exposure[String(q.id)]||0));const selected=eligible.filter(q=>(exposure[String(q.id)]||0)>0);const meta=never.map(q=>({id:q.id,cat:q.cat,difficulty:q.difficulty,cognitiveLevel:q.cognitiveLevel,concept:q.concept||'',coreTopicId:q.coreTopicId||null,prefix:prefix(q.id),sameStratumSelected:selected.filter(x=>x.cat===q.cat&&x.difficulty===q.difficulty&&x.cognitiveLevel===q.cognitiveLevel).length,sameConceptSelected:selected.filter(x=>x.cat===q.cat&&x.difficulty===q.difficulty&&(x.concept||'')===(q.concept||'')).length}));return {runs,eligible:eligible.length,selected:selected.length,never:never.length,neverIds:meta.map(x=>x.id),neverMeta:meta,neverByCategory:group(never,q=>q.cat),neverByDifficulty:group(never,q=>q.difficulty),neverByCognitive:group(never,q=>q.cognitiveLevel),neverByCatDifficultyCognitive:group(never,q=>[q.cat,q.difficulty,q.cognitiveLevel].join('|')),neverByPrefix:group(never,q=>prefix(q.id)),selectedByCatDifficultyCognitive:group(selected,q=>[q.cat,q.difficulty,q.cognitiveLevel].join('|')),exposureTop:Object.entries(exposure).sort((a,b)=>b[1]-a[1]).slice(0,20).map(([id,n])=>({id,n}))};}
const originalRandom=Math.random;const diag=runMixed(240);Math.random=originalRandom;const fullBp=MOCK_BLUEPRINTS.full,halfBp=MOCK_BLUEPRINTS.half;const out={v:APP_VERSION,diag,pickMockPool:String(pickMockPool),mockCognitivePreference:String(mockCognitivePreference),mockCandidateSort:String(mockCandidateSort),builder:String(buildMockQuestions),fullDifficultyByCat:allocateMockDifficultyByCategory(mockCategoryQuotas(fullBp.count),fullBp),halfDifficultyByCat:allocateMockDifficultyByCategory(mockCategoryQuotas(halfBp.count),halfBp),bankSignature:QUESTION_BANK.map(q=>[q.id,q.cat,q.difficulty,q.cognitiveLevel,q.concept,q.coreTopicId]),sem:validateSubjectBSemantics()};console.log('__V309__'+Buffer.from(JSON.stringify(out)).toString('base64'));
'''
    with tempfile.TemporaryDirectory() as td:
        p=Path(td)/'rt.js';p.write_text(stub+'\n'+js+'\n'+tail);z=subprocess.run(['node',str(p)],capture_output=True,text=True);req(z.returncode==0,'runtime failed '+z.stderr[-9000:]);m=re.search(r'__V309__([A-Za-z0-9+/=]+)',z.stdout);req(m,'marker');return json.loads(base64.b64decode(m.group(1)))
version,previous=context();req((version,previous)==('v309','v308'),'expects v309')
parent=subprocess.check_output(['git','rev-parse','origin/main'],text=True).strip();p308=Path('_regression/subject-a-mock-sequential-rotation-v308.fixture.json');req(p308.exists(),'v308 fixture');req(json.loads(p308.read_text()).get('result')=='PASS — SEQUENTIAL MOCK ROTATION CHARACTERIZED','v308 result')
expected={'.github/subject-a-mock-unreached-question-diagnosis/validate_audit.py','.github/workflows/subject-a-mock-unreached-question-diagnosis.yml'};generated={'index.html','manifest.webmanifest','sw.js','_regression/subject-a-mock-unreached-question-diagnosis-v309.fixture.json','audits/SUBJECT_A_MOCK_UNREACHED_QUESTION_DIAGNOSIS_v309.txt'};changed=set(subprocess.check_output(['git','diff','--name-only','origin/main...HEAD'],text=True).splitlines());req(expected<=changed,'missing source');req(changed<=expected|generated,'source drift '+repr(sorted(changed-(expected|generated))))
cand,par=runtime('_site/index.html'),runtime('_site_parent/index.html');req(cand['v']=='v309' and par['v']=='v308','versions');
for k in ['diag','pickMockPool','mockCognitivePreference','mockCandidateSort','builder','fullDifficultyByCat','halfDifficultyByCat','bankSignature']:req(cand[k]==par[k],k+' drift')
req(cand['sem'].get('ok') is True,'semantic');req('mockCognitivePreference' in cand['pickMockPool'],'pickMockPool cognitive path missing');req('mockCandidateSort' in cand['pickMockPool'],'pickMockPool novelty sort missing')
files=['index.html','manifest.webmanifest','sw.js','icon-192.png','icon-512.png','apple-touch-icon.png'];req(all((Path('_site')/x).read_bytes()==(Path('_site_reference')/x).read_bytes() for x in files),'reference mismatch')
diag=cand['diag'];never=diag['neverMeta'];all_have_same_stratum=all(x['sameStratumSelected']>0 for x in never);concept_sibling=sum(1 for x in never if x['sameConceptSelected']>0);summary={'mixedSequentialRuns':diag['runs'],'eligible':diag['eligible'],'selected':diag['selected'],'never':diag['never'],'neverByCategory':diag['neverByCategory'],'neverByDifficulty':diag['neverByDifficulty'],'neverByCognitive':diag['neverByCognitive'],'neverByCatDifficultyCognitive':diag['neverByCatDifficultyCognitive'],'neverByPrefix':diag['neverByPrefix'],'allNeverHaveSelectedSameStratum':all_have_same_stratum,'neverWithSelectedSameConcept':concept_sibling,'neverIds':diag['neverIds'],'neverMeta':never,'pickMockPoolSource':cand['pickMockPool'],'mockCognitivePreferenceSource':cand['mockCognitivePreference'],'difficultyAllocation':{'full':cand['fullDifficultyByCat'],'half':cand['halfDifficultyByCat']},'interpretation':'If unreached questions coexist with selected questions in the same category/difficulty/cognitive stratum, the issue is not a simple missing blueprint slot. Inspect concept-cap and greedy cognitive preference interaction before changing quotas or metadata.'}
fixture={'version':version,'previous':previous,'parent':parent,'result':'PASS — UNREACHED MOCK QUESTIONS DIAGNOSED','summary':summary,'semanticOK':True,'candidateReferenceSixFileByteEquality':True};Path('_regression').mkdir(exist_ok=True);Path('_regression/subject-a-mock-unreached-question-diagnosis-v309.fixture.json').write_text(json.dumps(fixture,ensure_ascii=False,indent=2)+'\n')
audit=f'''FE QUEST v309 — Subject A Mock Unreached-Question Diagnosis\n==============================================================\n\nResult\n------\nPASS — UNREACHED MOCK QUESTIONS DIAGNOSED\nPrevious release: v308\nSource main: {parent}\nLearner-facing change: none\n\nPurpose\n-------\nv308 found excellent adjacent-session rotation but only about 89% bank reachability after long sequential use. v309 classifies the remaining questions before any selector repair.\n\nSummary\n-------\n{json.dumps(summary,ensure_ascii=False,indent=2)}\n\nRegression\n----------\nNo question, blueprint, selector, profile schema or learner-facing behavior changed.\nSubject B semantic diagnostics: OK.\nCandidate/mechanical-reference six-file equality: yes.\n\nDecision\n--------\nUse the concrete unreached strata and pickMockPool/cognitive-preference evidence above to decide whether v310 should alter the selector. Do not weaken category/difficulty/cognitive blueprints merely to force 100% QUESTION_BANK exposure; some bank items may be intentionally better suited to lessons or drills than mocks.\n''';Path('audits').mkdir(exist_ok=True);Path('audits/SUBJECT_A_MOCK_UNREACHED_QUESTION_DIAGNOSIS_v309.txt').write_text(audit);print(audit)
