const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'../..');
const source=fs.readFileSync(path.join(root,'app/stack-queue-diagrams-v360.js'),'utf8');
const context=vm.createContext({escapeHtml:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')});
vm.runInContext(source,context);
const initial=()=>context.stackQueueInitialStateV360();
const apply=(s,op)=>context.stackQueueApplyV360(s,op);
const plain=x=>JSON.parse(JSON.stringify(x));
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
test('initial states are independent',()=>{let a=initial(),b=initial();a.stack.pop();assert.equal(b.stack.length,3);assert.equal(a.queue.length,3);});
test('LIFO removes C B A',()=>{let s=initial(),out=[];for(let i=0;i<3;i++){const r=apply(s,'pop');s=r.state;out.push(r.event.value);}assert.deepEqual(out,['C','B','A']);assert.equal(apply(s,'pop').event,null);});
test('FIFO removes A B C',()=>{let s=initial(),out=[];for(let i=0;i<3;i++){const r=apply(s,'dequeue');s=r.state;out.push(r.event.value);}assert.deepEqual(out,['A','B','C']);assert.equal(apply(s,'dequeue').event,null);});
test('PUSH changes the next stack output',()=>{const s=apply(initial(),'push').state;assert.equal(apply(s,'pop').event.value,'D');});
test('ENQUEUE does not overtake queued elements',()=>{let s=apply(initial(),'enqueue').state,out=[];for(let i=0;i<4;i++){const r=apply(s,'dequeue');s=r.state;out.push(r.event.value);}assert.deepEqual(out,['A','B','C','D']);});
test('state and before/after snapshots do not alias',()=>{const s=initial(),r=apply(s,'pop');assert.deepEqual(plain(s.stack),['A','B','C']);r.state.stack.push('X');assert.deepEqual(plain(r.event.after),['A','B']);assert.deepEqual(plain(r.event.before),['A','B','C']);});
test('six-cell display bound rejects further additions',()=>{for(const [op,key] of [['push','stack'],['enqueue','queue']]){let s=initial();for(let i=0;i<3;i++)s=apply(s,op).state;assert.equal(s[key].length,6);assert.equal(apply(s,op).event,null);}});
test('reset reconstructs initial arrays',()=>{const s=apply(initial(),'pop').state;assert.deepEqual(plain(apply(s,'reset').state),plain(initial()));});
test('unknown operation is a no-op',()=>{const s=initial(),r=apply(s,'unknown');assert.equal(r.event,null);assert.equal(r.state,s);});
test('generated sequence agrees with independent stack/queue operations',()=>{let s=initial(),seed=1;for(let i=0;i<600;i++){seed=(seed*1664525+1013904223)>>>0;const op=['push','pop','enqueue','dequeue','reset'][seed%5];const before=plain(s),r=apply(s,op);assert.deepEqual(plain(s),before);if(op!=='reset'&&r.event){const kind=['push','pop'].includes(op)?'stack':'queue',ref=before[kind];if(['push','enqueue'].includes(op))ref.push(r.event.value);else assert.equal(r.event.value,op==='pop'?ref.pop():ref.shift());assert.deepEqual(plain(r.state[kind]),ref);assert.deepEqual(plain(r.state[kind==='stack'?'queue':'stack']),before[kind==='stack'?'queue':'stack']);}s=r.state;assert.ok(s.stack.length<=6&&s.queue.length<=6);}});
test('shared visual displays TOP C B A and FRONT A B C',()=>{const s=initial(),html=context.stackQueueCardsV360(s.stack,s.queue),panels=html.split('data-sq-kind=');assert.deepEqual([...panels[1].matchAll(/data-sq-value="([^"]+)"/g)].map(m=>m[1]),['C','B','A']);assert.deepEqual([...panels[2].matchAll(/data-sq-value="([^"]+)"/g)].map(m=>m[1]),['A','B','C']);assert.deepEqual(plain(s),plain(initial()));});
test('visual values are escaped',()=>{const html=context.stackQueueCardsV360(['<img onerror="x">'],[]);assert.ok(!html.includes('<img'));assert.ok(html.includes('&lt;img'));});
test('core diagram only mounts for data structures',()=>{assert.ok(context.coreTopicStackQueueDiagramViewV360('core_03_01').includes('C → B → A'));for(const id of ['core_03_03','core_14_04','',null])assert.equal(context.coreTopicStackQueueDiagramViewV360(id),'');});
test('empty visuals have no next output',()=>{const html=context.stackQueueCardsV360([],[]);assert.equal((html.match(/空です/g)||[]).length,2);assert.ok(!html.includes('次に出る'));});
test('POP operation label is idempotent and does not rewrite POP3',()=>{const text='最初のPOPはCです。POP3 POP（取り出し操作）';const result=context.stackQueueOperationTextV360(text);assert.equal(result,'最初のPOP（取り出し操作）はCです。POP3 POP（取り出し操作）');assert.equal(context.stackQueueOperationTextV360(result),result);});
console.log(`PASS — V360 STACK QUEUE MODEL ${count}/${count}`);
