from pathlib import Path
import base64,json,os,re,runpy,subprocess,tempfile

def req(ok,msg):
    if not ok: raise AssertionError(msg)
def context():
    b=os.environ.get('GITHUB_HEAD_REF') or os.environ.get('GITHUB_REF_NAME') or subprocess.check_output(['git','branch','--show-current'],text=True).strip();m=re.fullmatch(r'subject-a-mock-excluded-route-discovery-(v(\d+))',b);req(m,'bad v311 branch');return m.group(1),f'v{int(m.group(2))-1}'
def scripts(path):
    h=Path(path).read_text();return '\n'.join(s for s in re.findall(r'<script(?:\s[^>]*)?>(.*?)</script>',h,re.S|re.I) if s.strip() and not s.lstrip().startswith('{'))
def runtime(path,excluded):
    js=scripts(path);stub=runpy.run_path('.github/release/runtime_stub.py')['STUB'];excluded_json=json.dumps(excluded,ensure_ascii=False)
    tail=r'''
function seeded(seed){let a=seed>>>0;return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
const excluded=__EXCLUDED__;
const exSet=new Set(excluded),originalRandom=Math.random,randomHits=Object.fromEntries(excluded.map(id=>[id,0]));
for(let i=0;i<2400;i++){Math.random=seeded(3110001+i*7919);for(const q of chooseRandomBalanced(10)){if(exSet.has(String(q.id)))randomHits[String(q.id)]++;}}
const cats=[...new Set(QUESTION_BANK.map(q=>q.cat))],prescriptionHits=Object.fromEntries(excluded.map(id=>[id,0]));
for(let ci=0;ci<cats.length;ci++){for(let i=0;i<500;i++){Math.random=seeded(3210001+ci*100000+i*7919);const xs=buildPrescriptionQuiz('rx:knowledge:'+cats[ci]);for(const q of xs){if(exSet.has(String(q.id)))prescriptionHits[String(q.id)]++;}}}
Math.random=originalRandom;
const excludedRows=excluded.map(id=>QUESTION_BANK.find(q=>String(q.id)===id)).filter(Boolean);
const out={v:APP_VERSION,excludedFound:excludedRows.length,randomHits,prescriptionHits,randomSource:String(chooseRandomBalanced),prescriptionSource:String(buildPrescriptionQuiz),weakSource:String(chooseWeakQuestions),bankSignature:QUESTION_BANK.map(q=>[q.id,q.cat,q.difficulty,q.cognitiveLevel,q.concept,q.coreTopicId]),sem:validateSubjectBSemantics()};console.log('__V311__'+Buffer.from(JSON.stringify(out)).toString('base64'));
'''.replace('__EXCLUDED__',excluded_json)
    with tempfile.TemporaryDirectory() as td:
        p=Path(td)/'rt.js';p.write_text(stub+'\n'+js+'\n'+tail);z=subprocess.run(['node',str(p)],capture_output=True,text=True);req(z.returncode==0,'runtime failed '+z.stderr[-9000:]);m=re.search(r'__V311__([A-Za-z0-9+/=]+)',z.stdout);req(m,'marker');return json.loads(base64.b64decode(m.group(1)))
version,previous=context();req((version,previous)==('v311','v310'),'expects v311')
parent=subprocess.check_output(['git','rev-parse','origin/main'],text=True).strip();p310=Path('_regression/subject-a-mock-calibration-closure-v310.fixture.json');p309=Path('_regression/subject-a-mock-unreached-question-diagnosis-v309.fixture.json');req(p310.exists() and p309.exists(),'prior fixtures missing');req(json.loads(p310.read_text()).get('result')=='PASS — MOCK CALIBRATION SEQUENCE CLOSED','v310 result');v309=json.loads(p309.read_text());excluded=v309['summary']['neverIds'];req(len(excluded)==78,'excluded count')
expected={'.github/subject-a-mock-excluded-route-discovery/validate_audit.py','.github/workflows/subject-a-mock-excluded-route-discovery.yml'};generated={'index.html','manifest.webmanifest','sw.js','_regression/subject-a-mock-excluded-route-discovery-v311.fixture.json','audits/SUBJECT_A_MOCK_EXCLUDED_ROUTE_DISCOVERY_v311.txt'};changed=set(subprocess.check_output(['git','diff','--name-only','origin/main...HEAD'],text=True).splitlines());req(expected<=changed,'missing source');req(changed<=expected|generated,'source drift '+repr(sorted(changed-(expected|generated))))
cand,par=runtime('_site/index.html',excluded),runtime('_site_parent/index.html',excluded);req(cand['v']=='v311' and par['v']=='v310','versions');
for k in ['excludedFound','randomHits','prescriptionHits','randomSource','prescriptionSource','weakSource','bankSignature']:req(cand[k]==par[k],k+' audit-only drift')
req(cand['sem'].get('ok') is True and par['sem'].get('ok') is True,'semantic');req(cand['excludedFound']==78,'excluded ids missing from bank');req('QUESTION_BANK.map(q=>q.cat)' in cand['randomSource'] and 'QUESTION_BANK.filter(q=>q.cat===c)' in cand['randomSource'],'random selector no longer spans the bank by category');req('QUESTION_BANK.filter(q=>q.cat===cat)' in cand['prescriptionSource'],'prescription selector no longer exposes category bank')
unseen_random=[id for id,n in cand['randomHits'].items() if n==0];unseen_pres=[id for id,n in cand['prescriptionHits'].items() if n==0];req(not unseen_random,'mock-excluded items not observed in random practice '+repr(unseen_random))
js=scripts('_site/index.html');occ=[m.start() for m in re.finditer(r'chooseRandomBalanced\s*\(',js)];snips=[re.sub(r'\s+',' ',js[max(0,i-180):i+260]) for i in occ[:8]];req(len(occ)>=2,'no production caller found for chooseRandomBalanced')
files=['index.html','manifest.webmanifest','sw.js','icon-192.png','icon-512.png','apple-touch-icon.png'];req(all((Path('_site')/x).read_bytes()==(Path('_site_reference')/x).read_bytes() for x in files),'reference mismatch')
hits=list(cand['randomHits'].values());phits=list(cand['prescriptionHits'].values());summary={'mockExcludedQuestions':78,'randomBalancedPracticeObserved':78,'randomBalancedSessions':2400,'randomHitMin':min(hits),'randomHitMedian':sorted(hits)[len(hits)//2],'randomHitMax':max(hits),'categoryPrescriptionObserved':sum(1 for n in phits if n>0),'categoryPrescriptionUnobserved':unseen_pres,'chooseRandomBalancedCallOccurrences':len(occ),'callSnippets':snips,'randomSelectorSource':cand['randomSource'],'prescriptionSelectorSource':cand['prescriptionSource'],'interpretation':'Every question excluded from the calibrated mock pool remains in QUESTION_BANK and was actually selected by the existing balanced-random practice selector. The selector builds category pools from the entire QUESTION_BANK without difficulty/cognitive exclusion. Therefore mock calibration does not make these questions unreachable to the learner.','decision':'KEEP MOCK CALIBRATION; NON-MOCK PRACTICE PRESERVES BANK REACHABILITY'}
fixture={'version':version,'previous':previous,'parent':parent,'result':'PASS — MOCK-EXCLUDED QUESTIONS REMAIN PRACTICE-REACHABLE','summary':summary,'semanticOK':True,'candidateReferenceSixFileByteEquality':True};Path('_regression').mkdir(exist_ok=True);Path('_regression/subject-a-mock-excluded-route-discovery-v311.fixture.json').write_text(json.dumps(fixture,ensure_ascii=False,indent=2)+'\n')
audit=f'''FE QUEST v311 — Subject A Mock-Excluded Route Reachability Audit\n================================================================\n\nResult\n------\nPASS — MOCK-EXCLUDED QUESTIONS REMAIN PRACTICE-REACHABLE\nPrevious release: v310\nSource main: {parent}\nLearner-facing change: none\n\nFinding\n-------\n{json.dumps(summary,ensure_ascii=False,indent=2)}\n\nRegression\n----------\nQUESTION_BANK and practice selector implementations are unchanged from v310.\nAll 78 v309 mock-excluded IDs still exist in the bank.\nAll 78 were observed through chooseRandomBalanced during deterministic practice simulation.\nSubject B semantic diagnostics: OK.\nCandidate/mechanical-reference six-file equality: yes.\n\nDecision\n--------\nDo not force cross-calibration questions into the mock. The calibrated mock and broad practice routes serve different purposes: the mock preserves exam-like composition, while existing random/category practice keeps the wider bank learnable. This closes the reachability concern without adding another selector layer.\n''';Path('audits').mkdir(exist_ok=True);Path('audits/SUBJECT_A_MOCK_EXCLUDED_ROUTE_DISCOVERY_v311.txt').write_text(audit);print(audit)
