const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium,webkit}=require('playwright');
const ROOT=path.resolve(__dirname,'../..');
const OUT=path.join(ROOT,'_browser_evidence/v367');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json'};
function server(){return http.createServer((req,res)=>{const pathname=new URL(req.url,'http://127.0.0.1').pathname;const rel=pathname==='/'||pathname==='/index.html'?'app/base-shell-v367.html':decodeURIComponent(pathname).replace(/^\/+/, '');const target=path.resolve(ROOT,rel);if(!target.startsWith(ROOT+path.sep)||!fs.existsSync(target)||!fs.statSync(target).isFile()){res.writeHead(404);res.end('not found');return}const body=fs.readFileSync(target);res.writeHead(200,{'content-type':types[path.extname(target)]||'application/octet-stream','content-length':body.length,'cache-control':'no-store'});res.end(body)})}
async function stable(page){const deadline=Date.now()+45000;for(let i=0;i<8;i++){const remain=Math.max(1000,deadline-Date.now());await page.waitForLoadState('load',{timeout:remain});await page.waitForFunction(()=>window.FEQUEST_APP_BOOT_COMPLETE===true&&window.__FEQ_PAGESHOW_SEEN===true,null,{timeout:remain});await page.waitForFunction(()=>navigator.serviceWorker.controller?.state==='activated',null,{timeout:remain});const origin=await page.evaluate(()=>performance.timeOrigin);await page.waitForTimeout(750);if(await page.evaluate(o=>performance.timeOrigin===o&&window.FEQUEST_APP_BOOT_COMPLETE===true,origin))return;if(Date.now()>=deadline)break}throw new Error('stable boot boundary not reached')}
async function layout(root){return root.evaluate(node=>{const blocks=[node,...node.querySelectorAll('section,div,p,h4,figcaption,code')];return{overflows:blocks.filter(n=>n.scrollWidth>n.clientWidth+1).map(n=>n.className||n.tagName),documentOverflow:document.documentElement.scrollWidth>innerWidth+1,cellWidths:[...node.querySelectorAll('[data-sort-index],[data-sort-trace-index]')].map(n=>n.getBoundingClientRect().width)}})}
async function runCase(type,name,viewport,isMobile=false){const browser=await type.launch();const context=await browser.newContext({viewport,locale:'ja-JP',isMobile,hasTouch:isMobile,deviceScaleFactor:isMobile?2:1});const page=await context.newPage();await page.addInitScript(()=>{window.__FEQ_PAGESHOW_SEEN=false;addEventListener('pageshow',()=>window.__FEQ_PAGESHOW_SEEN=true,{once:true})});const errors=[],checks=[],metrics={};page.on('pageerror',e=>errors.push(String(e)));const check=(label,value)=>{checks.push({label,pass:Boolean(value)});if(!value)throw new Error(label)};const snap=async(selector,suffix)=>{const n=page.locator(selector);await n.evaluate(node=>node.scrollIntoView({block:'center',inline:'nearest'}));await page.waitForTimeout(100);await page.screenshot({path:path.join(OUT,`${name}-${suffix}-context.png`)});await n.screenshot({path:path.join(OUT,`${name}-${suffix}.png`)})};try{const response=await page.goto(globalThis.__BASE__,{waitUntil:'load',timeout:60000});await stable(page);check('HTTP 200 and v367 runtime',response.status()===200&&await page.evaluate(()=>APP_VERSION==='v367'));await page.evaluate(()=>{profile.diagnosticCompleted=true;firstRunGuidedSessionV364=false;document.body.classList.remove('fequest-first-run-v364');document.getElementById('firstRunGuidedV364')?.remove()});const before=await page.evaluate(()=>({progress:{...profile.lessonProgress},bProgress:{...profile.bProgress},xp:profile.xp}));
  check('scope excludes other topics',await page.evaluate(()=>coreTopicSortDiagramViewV367('core_03_02')===''&&coreTopicSearchDiagramViewV366('core_03_03').includes('search-figure-v366')));
  await page.evaluate(()=>startLesson('core_03_03'));const figure=page.locator('.sort-figure-v367');await figure.waitFor({state:'visible'});check('one static figure and two panels',await figure.count()===1&&await figure.locator('.sort-panel-v367').count()===2);const text=await figure.innerText();check('bubble first pass exact',text.includes('[2, 4, 1, 5]')&&text.includes('最大値5が右端に確定'));check('selection first pass exact',text.includes('minPos = 3')&&text.includes('[1, 2, 5, 4]')&&text.includes('最小値1が左端に確定'));check('boundary and complexity',text.includes('1回では全体が完成するとは限らない')&&text.includes('O(n²)'));check('no controls or gate',await figure.locator('button').count()===0&&await page.evaluate(()=>lessonInteractiveDone));metrics.core=await layout(figure);check('core fits viewport',metrics.core.overflows.length===0&&!metrics.core.documentOverflow&&Math.min(...metrics.core.cellWidths)>=20);await snap('.sort-figure-v367','core');await page.evaluate(()=>startLesson('core_03_03'));check('rerender stays unique',await page.locator('.sort-figure-v367').count()===1);
  await page.evaluate(()=>{showScreen('trace',{instant:true});startBExercise('bubble_sort_b');const step=currentB.steps.find(s=>s.line===1&&s.state?.i===1);if(!step)throw new Error('bubble step missing');renderBVisual(step)});const bubble=page.locator('#bVisual .sort-trace-v367');await bubble.waitFor({state:'visible'});check('bubble trace shows adjacent comparison',await bubble.getAttribute('data-sort-mode')==='bubble'&&await bubble.getAttribute('data-sort-i')==='1'&&await bubble.locator('.is-compare').count()===2&&(await bubble.innerText()).includes('data[1] と data[2]'));metrics.bubble=await layout(bubble);check('bubble trace fits viewport',metrics.bubble.overflows.length===0&&!metrics.bubble.documentOverflow&&Math.min(...metrics.bubble.cellWidths)>=20);await snap('#bVisual .sort-trace-v367','bubble-trace');
  await page.evaluate(()=>{startBExercise('selection_sort_b');const step=currentB.steps.find(s=>s.line===2&&s.state?.j===2&&s.state?.minPos===1);if(!step)throw new Error('selection step missing');renderBVisual(step)});const selection=page.locator('#bVisual .sort-trace-v367');await selection.waitFor({state:'visible'});check('selection trace shows scan and candidate',await selection.getAttribute('data-sort-mode')==='selection'&&await selection.getAttribute('data-sort-j')==='2'&&await selection.getAttribute('data-sort-min-pos')==='1'&&await selection.locator('.is-candidate').count()===1&&await selection.locator('.is-scan').count()===1&&(await selection.innerText()).includes('添字1（値2）'));metrics.selection=await layout(selection);check('selection trace fits viewport',metrics.selection.overflows.length===0&&!metrics.selection.documentOverflow&&Math.min(...metrics.selection.cellWidths)>=20);await snap('#bVisual .sort-trace-v367','selection-trace');
  await page.evaluate(()=>{const step=currentB.steps.find(s=>s.line===8);renderBVisual(step)});check('selection completion fixes left edge',await selection.getAttribute('data-sort-complete')==='true'&&await selection.locator('.is-fixed').count()===1&&!(await selection.innerText()).includes('minPos'));
  const mock=await page.evaluate(()=>bMockVisualHtml({visual:{array:[5,1,4,2],arrayState:[1,5,4,2],sortMode:'bubble_sort_b',sortState:{i:0},sortLine:3,focus:1}}));check('mini mock uses sort renderer',mock.includes('data-sort-mode="bubble"')&&mock.includes('data-sort-i="0"'));const generic=await page.evaluate(()=>bMockVisualHtml({visual:{array:[4,9,2,7],focus:1}}));check('other arrays keep generic renderer',generic.includes('trace-array')&&!generic.includes('sort-trace-v367'));check('answer contracts unchanged',await page.evaluate(()=>B_PREDICTION_CONTRACTS['bubble_sort_b:1']==='[1,5,4,2]'&&B_PREDICTION_CONTRACTS['bubble_sort_b:2']==='[1,4,2,5]'&&B_PREDICTION_CONTRACTS['selection_sort_b:1']==='1'&&B_PREDICTION_CONTRACTS['selection_sort_b:2']==='3'));check('saved learning unchanged',JSON.stringify(await page.evaluate(()=>({progress:{...profile.lessonProgress},bProgress:{...profile.bProgress},xp:profile.xp})))===JSON.stringify(before));check('no errors or recovery UI',errors.length===0&&await page.locator('#fequestAssetRecoveryV367').count()===0);return{name,checks,metrics,errors,pass:true}
}catch(error){try{await page.screenshot({path:path.join(OUT,`${name}-failure.png`),fullPage:true})}catch{}return{name,checks,metrics,errors,error:error.stack||String(error),pass:false}}finally{await context.close();await browser.close()}}
async function main(){fs.mkdirSync(OUT,{recursive:true});const app=server();await new Promise(r=>app.listen(0,'127.0.0.1',r));globalThis.__BASE__=`http://127.0.0.1:${app.address().port}/`;let cases;try{cases=[await runCase(chromium,'desktop-chromium-1366',{width:1366,height:900}),await runCase(chromium,'tablet-chromium-1024',{width:1024,height:768}),await runCase(webkit,'mobile-webkit-390',{width:390,height:844},true),await runCase(webkit,'narrow-webkit-320',{width:320,height:720},true)]}finally{await new Promise(r=>app.close(r))}const report={name:'v367-sort-diagrams',cases,result:cases.every(c=>c.pass)?'PASS':'FAIL'};fs.writeFileSync(path.join(OUT,'result.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(report.result!=='PASS')process.exitCode=1}
main().catch(e=>{console.error(e);process.exitCode=1});
